import { existsSync, readFileSync, writeFileSync, renameSync, chmodSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

export const HOOKIFY_MARKER = '# Generated by Hookify';

export const HOOK_TYPES = ['pre-commit', 'commit-msg'];

export function decideHookAction(existingContent) {
  if (existingContent === null) return 'create';
  if (existingContent.includes(HOOKIFY_MARKER)) return 'overwrite';
  return 'backup-and-replace';
}

// A project name is free-text user input (unlike check.id/check.run, which
// come from the hardcoded ChecksCatalog on the server). It only ever ends
// up inside a shell comment line here, so quotes/$()/backticks are inert —
// but a literal newline would break out of the comment and turn the rest
// of the name into its own, unintended shell statement in the generated
// hook. Stripped defensively even though the server also validates this,
// since the CLI shouldn't have to trust the server to stay safe.
function sanitizeForComment(value) {
  return String(value).replace(/[\r\n]/g, ' ');
}

export function renderHook(hookName, projectName, checks) {
  const lines = [
    '#!/bin/sh',
    HOOKIFY_MARKER,
    `# Project: ${sanitizeForComment(projectName)}`,
    `# Hook: ${hookName}`,
    '# Do not edit — this file is regenerated by `hookify sync`.',
    '',
    'set -e',
    '',
  ];

  for (const check of checks) {
    lines.push(
      `echo "[Hookify] ${check.id}"`,
      `${check.run} || {`,
      `  echo "[Hookify] ${check.id} failed. Commit aborted."`,
      '  exit 1',
      '}',
      '',
    );
  }

  return lines.join('\n');
}

export function installHook(gitDir, hookName, projectName, checks) {
  const hookPath = join(gitDir, 'hooks', hookName);
  const existing = existsSync(hookPath) ? readFileSync(hookPath, 'utf8') : null;
  const action = decideHookAction(existing);

  let backupPath;
  if (action === 'backup-and-replace') {
    backupPath = `${hookPath}.backup.${Date.now()}`;
    renameSync(hookPath, backupPath);
  }

  writeFileSync(hookPath, renderHook(hookName, projectName, checks), 'utf8');
  chmodSync(hookPath, 0o755);

  return { action, backupPath };
}

export function removeManagedHook(gitDir, hookName) {
  const hookPath = join(gitDir, 'hooks', hookName);
  if (!existsSync(hookPath)) return false;

  const content = readFileSync(hookPath, 'utf8');
  if (!content.includes(HOOKIFY_MARKER)) return false;

  unlinkSync(hookPath);
  return true;
} 