import { existsSync, readFileSync, writeFileSync, renameSync, chmodSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

export const HOOKIFY_MARKER = '# Generated by Hookify';

// Known git hook types managed by Hookify. Extended with a single line
// (e.g. adding 'pre-push' in v2.0) — the rest of the CLI's logic is
// already built for an arbitrary set of types coming from manifest.hooks.
export const HOOK_TYPES = ['pre-commit', 'commit-msg'];

/**
 * Decides what to do with an already-existing hook file.
 * Kept separate from file operations so it can be tested without disk I/O.
 *
 * @returns {'create'|'overwrite'|'backup-and-replace'}
 */
export function decideHookAction(existingContent) {
  if (existingContent === null) return 'create';
  if (existingContent.includes(HOOKIFY_MARKER)) return 'overwrite';
  return 'backup-and-replace';
}

/**
 * Renders a hook script for an arbitrary hook type. For commit-msg, the
 * commands in the manifest already contain a literal `"$1"` (the path to
 * the commit message file) — git itself passes that when invoking the
 * hook, the template here doesn't substitute anything special, it just
 * outputs the command as-is.
 */
export function renderHook(hookName, projectName, checks) {
  const lines = [
    '#!/bin/sh',
    HOOKIFY_MARKER,
    `# Project: ${projectName}`,
    `# Hook: ${hookName}`,
    '# Do not edit — this file is regenerated by `hookify sync`.',
    '',
    'set -e',
    '',
  ];

  for (const check of checks) {
    lines.push(
      `echo "[Hookify] ${check.id}"`,
      `${check.run} || {`,
      `  echo "[Hookify] ${check.id} failed. Commit aborted."`,
      '  exit 1',
      '}',
      '',
    );
  }

  return lines.join('\n');
}

/**
 * Writes a hook of the given type without silently overwriting a foreign one.
 *
 * @returns {{action: string, backupPath?: string}}
 */
export function installHook(gitDir, hookName, projectName, checks) {
  const hookPath = join(gitDir, 'hooks', hookName);
  const existing = existsSync(hookPath) ? readFileSync(hookPath, 'utf8') : null;
  const action = decideHookAction(existing);

  let backupPath;
  if (action === 'backup-and-replace') {
    // A foreign hook (Husky etc.) — back it up before replacing.
    // Silently overwriting someone else's setup is the #1 way to lose
    // trust in a CLI.
    backupPath = `${hookPath}.backup.${Date.now()}`;
    renameSync(hookPath, backupPath);
  }

  writeFileSync(hookPath, renderHook(hookName, projectName, checks), 'utf8');
  chmodSync(hookPath, 0o755);

  return { action, backupPath };
}

/**
 * Removes a hook if it was previously installed by Hookify (the marker is
 * present) and no check is enabled for its type anymore. Leaves the hook
 * alone entirely if the marker is missing — that's either a foreign file
 * or one we never installed; removing something foreign without an
 * explicit user request is just as unacceptable as silently overwriting it.
 *
 * @returns {boolean} true if the file was removed
 */
export function removeManagedHook(gitDir, hookName) {
  const hookPath = join(gitDir, 'hooks', hookName);
  if (!existsSync(hookPath)) return false;

  const content = readFileSync(hookPath, 'utf8');
  if (!content.includes(HOOKIFY_MARKER)) return false;

  unlinkSync(hookPath);
  return true;
}