import { existsSync, readFileSync, writeFileSync, renameSync, chmodSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

export const HOOKIFY_MARKER = '# Generated by Hookify';

// Известные типы git-хуков, которыми управляет Hookify. Расширяется одной
// строкой (например, добавить 'pre-push' в v2.0), остальная логика CLI
// уже рассчитана на произвольный набор типов из manifest.hooks.
export const HOOK_TYPES = ['pre-commit', 'commit-msg'];

/**
 * Решает, что делать с уже существующим файлом хука.
 * Вынесено отдельно от файловых операций, чтобы тестировать без диска.
 *
 * @returns {'create'|'overwrite'|'backup-and-replace'}
 */
export function decideHookAction(existingContent) {
  if (existingContent === null) return 'create';
  if (existingContent.includes(HOOKIFY_MARKER)) return 'overwrite';
  return 'backup-and-replace';
}

/**
 * Рендерит скрипт хука произвольного типа. Для commit-msg команды в
 * манифесте уже содержат буквальный `"$1"` (путь к файлу с сообщением
 * коммита) — это передаёт сам git при вызове хука, шаблон здесь ничего
 * специально не подставляет, просто выводит команду как есть.
 */
export function renderHook(hookName, projectName, checks) {
  const lines = [
    '#!/bin/sh',
    HOOKIFY_MARKER,
    `# Project: ${projectName}`,
    `# Hook: ${hookName}`,
    '# Do not edit — this file is regenerated by `hookify sync`.',
    '',
    'set -e',
    '',
  ];

  for (const check of checks) {
    lines.push(
      `echo "[Hookify] ${check.id}"`,
      `${check.run} || {`,
      `  echo "[Hookify] ${check.id} failed. Commit aborted."`,
      '  exit 1',
      '}',
      '',
    );
  }

  return lines.join('\n');
}

/**
 * Пишет хук заданного типа, не затирая чужой молча.
 *
 * @returns {{action: string, backupPath?: string}}
 */
export function installHook(gitDir, hookName, projectName, checks) {
  const hookPath = join(gitDir, 'hooks', hookName);
  const existing = existsSync(hookPath) ? readFileSync(hookPath, 'utf8') : null;
  const action = decideHookAction(existing);

  let backupPath;
  if (action === 'backup-and-replace') {
    // Чужой хук (Husky и т.п.) — сохраняем перед заменой.
    // Затирать чужие настройки молча — главный способ потерять доверие к CLI.
    backupPath = `${hookPath}.backup.${Date.now()}`;
    renameSync(hookPath, backupPath);
  }

  writeFileSync(hookPath, renderHook(hookName, projectName, checks), 'utf8');
  chmodSync(hookPath, 0o755);

  return { action, backupPath };
}

/**
 * Снимает хук, если он раньше был поставлен Hookify (есть маркер) и для
 * его типа теперь не включено ни одного чека. Не трогает хук вообще, если
 * маркера нет — это либо чужой файл, либо мы его никогда не устанавливали;
 * снимать чужое без явного запроса пользователя недопустимо, ровно как
 * недопустимо было бы его тихо перезаписывать.
 *
 * @returns {boolean} true, если файл был снят
 */
export function removeManagedHook(gitDir, hookName) {
  const hookPath = join(gitDir, 'hooks', hookName);
  if (!existsSync(hookPath)) return false;

  const content = readFileSync(hookPath, 'utf8');
  if (!content.includes(HOOKIFY_MARKER)) return false;

  unlinkSync(hookPath);
  return true;
}